### ISSUE TITLE
Soil Health - Regulation: Look into how nutrients and water can be mixed autonomously

### ISSUE THREAD

**Issue by isombeg** [Plant-Monitor/Plant-Monitor-Device#1]

**Comment by timiagiri** [comment]
https://topsoilpros.com/5-ways-to-add-nutrients-to-soil/
- this link talks about Epsom salt as a good source of nutrients for plants; we could potentially keep that in a solution or mix them in the system.
https://www.growbarato.net/blog/en/long-can-keep-water-tank/
- I need to look into mineral nutrients, as those can apparently stay in water a lot longer than organic nutrients

**Comment by isombeg** [comment]
Tawana believes we can just mix water and nutrients in the tube
