### ISSUE TITLE
Order all hardware and inform team of cost per person

### ISSUE THREAD

**Issue by isombeg** [Plant-Monitor/Plant-Monitor-Device#11]

**Comment by timiagiri** [comment]
https://www.sparkfun.com/products/19222
- this could be nicely sized pump for our small operation; it's 12V so we'll need to keep that in mind

**Comment by timiagiri** [comment]
I will start building a "bill of materials" and share it here to add our proposed items 
when we decide on the our scope and how our design will look, we can order them
