### ISSUE TITLE
Research moisture sensors

### ISSUE THREAD

**Issue by isombeg** [Plant-Monitor/Plant-Monitor-Device#4]

**Comment by timiagiri** [comment]
https://lastminuteengineers.com/soil-moisture-sensor-arduino-tutorial/
- This looks like it will be valuable for when we start interfacing the sensors with our microcontroller(s)

**Comment by timiagiri** [comment]
TDR Soil Moisture and Temperature Profile Sensor: 
- https://www.campbellsci.ca/soilvue10 
- "Digital output is compatible with most data Campell Scientific data loggers" potentially an extra system we don't need, but precision and depth seems to be good
- pricing information not available yet

>

**Comment by timiagiri** [comment]
Here's another cool resource for the type of sensors that we might use, based on our needs:
- https://www.metergroup.com/en/meter-environment/measurement-insights/which-soil-moisture-sensor-perfect-you

**Comment by timiagiri** [comment]
Yet another resource:
- https://www.youtube.com/watch?v=pgGpuws7f9o

**Comment by timiagiri** [comment]
Spark Fun soil moisture sensor
- https://www.sparkfun.com/products/13322
- only downside may be size

**Comment by isombeg** [comment]
- Look into delivery times

**Comment by isombeg** [comment]
All good to close?

**Comment by timiagiri** [comment]
Yes sir
