### ISSUE TITLE
Research water level sensors

### ISSUE THREAD

**Issue by isombeg** [Plant-Monitor/Plant-Monitor-Device#5]

**Comment by timiagiri** [comment]
https://lastminuteengineers.com/water-level-sensor-arduino-tutorial/#:~:text=The%20water%20level%20sensor%20is%20extremely%20simple%20to%20use%20and,from%203.3V%20to%205V.

**Comment by timiagiri** [comment]
https://arduinogetstarted.com/tutorials/arduino-water-sensor

**Comment by isombeg** [comment]
Ready for closing?
