### ISSUE TITLE
Research sensors for monitoring humidity

### ISSUE THREAD

**Issue by isombeg** [Plant-Monitor/Plant-Monitor-Device#7]

**Comment by timiagiri** [comment]
https://www.sparkfun.com/products/16618
- this is the lowest-cost one I found
- I have also attached a picture showing what I assume is the typical delivery window for these devices from Sparkfun
![Screen Shot 2022-12-06 at 6 25 22 PM](https://user-images.githubusercontent.com/43770960/206047052-ed58a525-a02a-407c-ac7d-a04eda65e96a.png)

**Comment by isombeg** [comment]
Closeable?
